version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    # command: "gunicorn --bind 0:8000 main:app --worker-class uvicorn.workers.UvicornWorker"
    command: "uvicorn main:app --reload --host=0.0.0.0"
    ports:
      - 8002:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/postgres/data
    ports:
      - 15432:5432
